### ISSUE TITLE
Building failed with CERTCLILib not found

### ISSUE THREAD

**Issue by s3c** [GhostPack/Certify#2]
Not sure if I'm missing something obvious, as I'm not familiar with .NET, but getting the following error when building.

`1>C:\Users\User\Desktop\Certify-main\Certify\Lib\Cert.cs(4,7,4,17): error CS0246: The type or namespace name 'CERTCLILib' could not be found (are you missing a using directive or an assembly reference?)
`

**Comment by leechristensen** [comment]
This looks like the same errors as #6 and should be fixed now with 4c24a835527e5524d5fd2777fc7185422cf5fe4d. If you could test and verify, please let us know if it solved your problem! If there are issues, please comment in issue #6 . Thanks for the report!
