### ISSUE TITLE
Virus alert

### ISSUE THREAD

**Issue by jpcapone** [GhostPack/Certify#29]
When I compile certify.exe my computer alerts that there is a virus and the file is immediately deleted.  I am hesitant to disable anti virus but is that the only option?

**Comment by 0x10f2c** [comment]
could be bad

**Comment by hvprvtr** [comment]
This is hacktool. Antivirus reaction is normal here. Make a exclude folder for it and build it there.

**Comment by jpcapone** [comment]
> This is hacktool. Antivirus reaction is normal here. Make a exclude folder for it and build it there.

Thanks for the confirmation.  I have used this tool several times since this post so I should have closed it out.  Thanks again!!
