### ISSUE TITLE
[help wanted] AD CS /certsrv Endpoint authentication failed.

### ISSUE THREAD

**Issue by kmahyyg** [GhostPack/Certify#4]
First of all, thanks for your excellent research work.

I'm trying to reproduce it using a Windows Server 2012 R2 with no patches installed either automatically or manually.

I installed AD CS using all default options offered by the setup wizard.

When I invoke the Python script from https://github.com/topotam/PetitPotam and cooperate it with `ntlmrelayx` from https://github.com/ExAndroidDev/impacket/tree/ntlmrelayx-adcs-attack , it just kept telling me HTTP 401 Unauthorized.

Since it's totally all default situation, I have no idea what's wrong with it to reproduce.

More information might be useful for debugging:

- Certificate can be requested via any other machine in the domain. DC itself also has a certificate. Any other machine also can request machine account certificate in GUI.
- Web Endpoint `/certsrv` will ask for human user credential, then it works as intended. But in this situation, machine account NTLM authentication seems not to work.
- If I replace `ntlmrelayx` with `responder`, I could successfully get a response and hash captured notice from `responder`, which means, at least, NTLM Relay part, works fine.

Thanks for your help in advance.

**Comment by leechristensen** [comment]
Sorry, this repository is only for reporting issues in Certify. We can't troubleshoot ntlmrelayx's code since it's not our codebase and is outside our control. You may consider commenting on the [ntlmrelay PR](https://github.com/SecureAuthCorp/impacket/pull/1101) associated with the AC CS functionality to help better that tool.
